Update bitrise (WIP)

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,80 +1,101 @@
 ---
-format_version: '5'
+format_version: '6'
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 project_type: android
+template:
+  create-release-template:
+    workflow: prompt
+    envs:
+    - RELEASE_VERSION_NUMBER:
+        opts:
+          title: The version number for the release
 workflows:
-  vdt:
+  deploy:
+    description: |
+      ## How to get a signed APK
+
+      This workflow contains the **Sign APK** step. To sign your APK all you have to do is to:
+
+      1. Click on **Code Signing** tab
+      1. Find the **ANDROID KEYSTORE FILE** section
+      1. Click or drop your file on the upload file field
+      1. Fill the displayed 3 input fields:
+       1. **Keystore password**
+       1. **Keystore alias**
+       1. **Private key password**
+      1. Click on **[Save metadata]** button
+
+      That's it! From now on, **Sign APK** step will receive your uploaded files.
+
+      ## To run this workflow
+
+      If you want to run this workflow manually:
+
+      1. Open the app's build list page
+      2. Click on **[Start/Schedule a Build]** button
+      3. Select **deploy** in **Workflow** dropdown input
+      4. Click **[Start Build]** button
+
+      Or if you need this workflow to be started by a GIT event:
+
+      1. Click on **Triggers** tab
+      2. Setup your desired event (push/tag/pull) and select **deploy** workflow
+      3. Click on **[Done]** and then **[Save]** buttons
+
+      The next change in your repository that matches any of your trigger map event will start **deploy** workflow.
     steps:
-    - activate-ssh-key:
+    - activate-ssh-key@4.0.3:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
     - git-clone@4.0.11: {}
     - cache-pull@2.0.1: {}
-    - install-missing-android-tools@2.2.0: {}
-    - gradle-runner@1.8.3:
+    - install-missing-android-tools@2.2.0:
         inputs:
-        - gradle_task: assembleDebug assembleDebugAndroidTest
-        title: Build APK
-    - virtual-device-testing-for-android@1.0.2:
+        - gradlew_path: "$PROJECT_LOCATION/gradlew"
+    - android-build@0.9.5:
         inputs:
-        - test_devices: |-
-            NexusLowRes,26,en,portrait
-            Nexus4,21,en,portrait
-        - test_type: instrumentation
-    - deploy-to-bitrise-io: {}
+        - project_location: "$PROJECT_LOCATION"
+        - module: "$MODULE"
+        - variant: release
+    - sign-apk@1.2.3:
+        run_if: '{{getenv "BITRISEIO_ANDROID_KEYSTORE_URL" | ne ""}}'
+    - fastlane@2.3.12:
+        inputs:
+        - update_fastlane: 'false'
+        - lane: release
+    - deploy-to-bitrise-io@1.3.15: {}
     - cache-push@2.0.5: {}
-  primary-backup:
+  prompt:
     steps:
-    - avd-manager@0.9.2:
-        inputs:
-        - version: '27'
-    - activate-ssh-key@3.1.1:
-        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
-    - git-clone@4.0.11: {}
-    - cache-pull@2.0.1: {}
     - script@1.1.5:
-        title: Do anything with Script step
-    - install-missing-android-tools@2.1.1: {}
-    - gradle-runner@1.8.3:
         inputs:
-        - gradle_task: assembleDebug
-        title: Build APK
-    - android-lint@0.9.2:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # write your script here
+            echo "Hello World!"
+
+            echo "Running release for $BITRISE_GIT_TAG - Release notes: $RELEASE_NOTES"
+
+            # or run a script from your repository, like:
+            # bash ./path/to/script.sh
+            # not just bash, e.g.:
+            # ruby ./path/to/script.rb
+    - fastlane@2.3.12:
         inputs:
-        - project_location: "$PROJECT_LOCATION"
-        - module: "$MODULE"
-        - variant: "$TEST_VARIANT"
-    - android-unit-test@0.9.3:
-        inputs:
-        - project_location: "$PROJECT_LOCATION"
-        - module: "$MODULE"
-        - variant: "$TEST_VARIANT"
-        title: Run JVM Unit Tests
-    - wait-for-android-emulator@1.0.4: {}
-    - gradle-runner@1.8.3:
-        inputs:
-        - gradle_task: connectedDebugAndroidTest
-        title: Run Instrumentation Tests
-    - deploy-to-bitrise-io@1.3.12: {}
-    - cache-push@2.0.5: {}
+        - lane: release
 app:
   envs:
   - opts:
       is_expand: false
     PROJECT_LOCATION: "."
-  - opts:
-      is_expand: false
-    GRADLEW_PATH: gradlew
-  - opts:
-      is_expand: false
-    MODULE: app
+  - MODULE: app
   - opts:
       is_expand: false
     BUILD_VARIANT: Debug
   - opts:
       is_expand: false
     TEST_VARIANT: Debug
-trigger_map:
-- push_branch: feature/*
-  workflow: vdt
-- pull_request_source_branch: "*"
-  workflow: vdt
